//
// String.swift
// Created by Arpit Williams on 11/07/24.
// Copyright (c) 2024 StarKnights Technologies

import Foundation

extension String {
  static let add = String(localized: "add", bundle: .module)
  static let addFiles = String(localized: "add_files", bundle: .module)
  static let addFolder = String(localized: "add_folder", bundle: .module)
  static let addPhotos = String(localized: "add_photos", bundle: .module)
  static let archivingFiles = String(localized: "archiving_files", bundle: .module)
  static let cancel = String(localized: "cancel", bundle: .module)
  static let copy = String(localized: "copy", bundle: .module)
  static let dataInTransit = String(localized: "data_in_transit", bundle: .module)
  static let date = String(localized: "date", bundle: .module)
  static let delete = String(localized: "delete", bundle: .module)
  static let done = String(localized: "done", bundle: .module)
  static let downloadLink = String(localized: "download_link", bundle: .module)
  static let downloadLinkInfo = String(localized: "download_link_info", bundle: .module)
  static let dropFiles = String(localized: "drop_files", bundle: .module)
  static let easyShare = String(localized: "easy_share", bundle: .module)
  static let fileCount = String(localized: "file_count", bundle: .module)
  static let fileFlyer = String(localized: "file_flyer", bundle: .module)
  static let fileName = String(localized: "file_name", bundle: .module)
  static let folderName = String(localized: "folder_name", bundle: .module)
  static let maxFileSize = String(localized: "max_file_size", bundle: .module)
  static let move = String(localized: "move", bundle: .module)
  static let name = String(localized: "name", bundle: .module)
  static let orTapBelow = String(localized: "or_tap_below", bundle: .module)
  static let overWifi = String(localized: "over_wifi", bundle: .module)
  static let pleaseDontKill = String(localized: "please_dont_kill", bundle: .module)
  static let pleaseWait = String(localized: "please_wait", bundle: .module)
  static let preview = String(localized: "preview", bundle: .module)
  static let recieveFiles = String(localized: "recieve_files", bundle: .module)
  static let rename = String(localized: "rename", bundle: .module)
  static let renameFile = String(localized: "rename_file", bundle: .module)
  static let scanCode = String(localized: "scan_code", bundle: .module)
  static let scanNote = String(localized: "scan_note", bundle: .module)
  static let scanToDownload = String(localized: "scan_to_download", bundle: .module)
  static let scanToUpload = String(localized: "scan_to_upload", bundle: .module)
  static let select = String(localized: "select", bundle: .module)
  static let selectFiles = String(localized: "select_files", bundle: .module)
  static let send = String(localized: "send", bundle: .module)
  static let sendFiles = String(localized: "send_files", bundle: .module)
  static let share = String(localized: "share", bundle: .module)
  static let size = String(localized: "size", bundle: .module)
  static let sortBy = String(localized: "sort_by", bundle: .module)
  static let spaceIsEmpty = String(localized: "space_is_empty", bundle: .module)
  static let speed = String(localized: "speed", bundle: .module)
  static let speedOfNow = String(localized: "speed_of_now", bundle: .module)
  static let tapTheIcon = String(localized: "tap_the_icon", bundle: .module)
  static let time = String(localized: "time", bundle: .module)
  static let transferredIn = String(localized: "transferred_in", bundle: .module)
  static let type = String(localized: "type", bundle: .module)
  static let uploadLink = String(localized: "upload_link", bundle: .module)
  static let uploadLinkInfo = String(localized: "upload_link_info", bundle: .module)
}
