//
// Symbols.swift
// Created by Arpit Williams on 27/05/24.
// Copyright (c) 2024 StarKnights Technologies

let checkmark = "checkmark"
let checkmarkCircle = "checkmark.circle"
let checkmarkCircleFill = "checkmark.circle.fill"
let chevronDown = "chevron.down"
let chevronUp = "chevron.up"
let chevronLeft = "chevron.left"
let doc = "doc"
let docFill = "doc.fill"
let docOnDoc = "doc.on.doc"
let docOnClipboard = "doc.on.clipboard"
let docZipped = "doc.zipper"
let downArrow = iOS17 ? "arrowshape.down.fill" : "arrowtriangle.down.fill"
let ellipsisCircleFill = "ellipsis.circle.fill"
let eye = "eye"
let folder = "folder"
let folderFill = "folder.fill"
let folderFillBadgePlus = "folder.fill.badge.plus"
let gearshapeFill = "gearshape.fill"
let lightBulbOff = iOS17 ? "lightbulb.min" : "lightbulb"
let lightBulbOn = iOS17 ? "lightbulb.max.fill" : "lightbulb.fill"
let link = "link"
let pencil = "pencil"
let photo = iOS17 ? "photo.badge.plus.fill" : "photo.fill"
let squareGrid3x3 = "square.grid.3x3"
let squareAndArrowUp = "square.and.arrow.up"
let upArrow = iOS17 ? "arrowshape.up.fill" : "arrowtriangle.up.fill"
let trash = "trash"
let trashCircle = "trash.circle"
let xmarkCircleFill = "xmark.circle.fill"
